name: "Set Issue Label and Assignee"
on:
  issues:
    types: [opened]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@v2.0.2
        with:
          body: "both"
          parameters: >-
            [
              {
                "keywords": ["visual bug"],
                "labels": ["B: visual"]
              },
              {
                "keywords": ["AUR", "Chocolatey", "PortableApps", "winget", "Scoop"],
                "labels": ["B: Unofficial Download"]
              },
              {
                "keywords": ["keyboard control not working"],
                "labels": ["B: keyboard control"]
              },
              {
                "keywords": ["text/string issue"],
                "labels": ["B: text/string"]
              },
              {
                "keywords": ["content not loading"],
                "labels": ["B: content not loading"]
              },
              {
                "keywords": ["accessibility issue"],
                "labels": ["B: accessibility"]
              },
              {
                "keywords": ["usability issue"],
                "labels": ["B: usability"]
              },
              {
                "keywords": ["causes crash"],
                "labels": ["B: crash"]
              },
              {
                "keywords": ["feature stopped working"],
                "labels": ["B: feature stopped working"]
              },
              {
                "keywords": ["inconsistent behavior"],
                "labels": ["B: inconsistent behavior"]
              },
              {
                "keywords": ["data loss"],
                "labels": ["B: data loss"]
              },
              {
                "keywords": ["race condition"],
                "labels": ["B: race condition"]
              },
              {
                "keywords": ["API issue"],
                "labels": ["B: API issue"]
              },
              {
                "keywords": ["only happens in developer mode"],
                "labels": ["B: developer mode"]
              },
              {
                "keywords": ["improvement to existing feature"],
                "labels": ["E: improvement existing feature"]
              },
              {
                "keywords": ["new optional setting"],
                "labels": ["E: new optional setting"]
              },
              {
                "keywords": ["visual improvement"],
                "labels": ["E: visual improvement"]
              },
              {
                "keywords": ["display more information to user"],
                "labels": ["E: display more information"]
              },
              {
                "keywords": ["ease of use improvement"],
                "labels": ["E: ease of use improvement"]
              },
              {
                "keywords": ["support for external software"],
                "labels": ["E: support external software"]
              },
              {
                "keywords": ["new feature"],
                "labels": ["E: new feature"]
              },
              {
                "keywords": ["new keyboard shortcut"],
                "labels": ["E: keyboard shortcut"]
              }
            ]
          github-token: "${{ secrets.GITHUB_TOKEN }}"
