name: 'Close stale PRs'
on:
  schedule:
    - cron: '30 1 * * *'

permissions: {}

jobs:
  stale:
    # As this action runs on a schedule, only run it in the FreeTubeApp/FreeTube repository to avoid unnecessary GitHub Actions usage/billing in forks.
    # If a fork does need this workflow, they can change this condition in their fork to include their repository.
    if: github.repository == 'FreeTubeApp/FreeTube'

    runs-on: ubuntu-latest

    permissions:
      actions: write
      pull-requests: write

    steps:
      - uses: actions/stale@997185467fa4f803885201cee163a9f38240193d #v10.1.1
        with:
          stale-pr-message: 'This PR is stale because it has been open 14 days with no activity. Remove stale label or comment or this will be closed in 14 days.'
          close-pr-message: 'This PR was closed because it has been stalled for 14 days with no activity.'
          days-before-pr-stale: 14
          days-before-pr-close: 14
          stale-pr-label: 'PR: stale'
          exempt-pr-labels: 'PR: WIP'
